=== Navarone/WBA2_SS13_Phase2/WBA2_Phase2/src/benutzer/Benutzer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Benutzer" xmlns:tns="http://www.example.org/Benutzer" elementFormDefault="qualified">
	<xs:element name="Benutzerprofile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Benutzer" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Id" type="xs:int"/>
							<xs:element name="Benutzername" type="xs:string"/>
							<xs:element name="Passwort" type="xs:string"/>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Vorname" type="xs:string"/>
							<xs:element name="EMail">
								<xs:simpleType>
    								<xs:restriction base="xs:string">
       									<xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
   									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Anmeldedatum" type="xs:date"/>
							<xs:element name="Adresse">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Strasse" type="xs:string"/>
										<xs:element name="Hausnummer" type="xs:int"/>
										<xs:element name="PLZ" type="xs:int"/>
										<xs:element name="Ort" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="AnzahlSchnaeppchen" type="xs:int"/>
							<xs:element name="GemeldeteSchnaeppchen">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Schnaeppchen" type="xs:int" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Bewertung" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Navarone/WBA2_SS13_Phase2/WBA2_Phase2/src/Benutzer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Benutzerprofile xmlns:tns="http://www.example.org/Benutzer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Benutzer Benutzer.xsd ">
  <tns:Benutzer>
    <tns:Id>2</tns:Id>
    <tns:Benutzername>SchnaeppchenJaeger</tns:Benutzername>
    <tns:Passwort>humbuck156</tns:Passwort>
    <tns:Name>Mustermann</tns:Name>
    <tns:Vorname>Max</tns:Vorname>
    <tns:EMail>Max@Muster.Mann</tns:EMail>
    <tns:Anmeldedatum>2010-12-12</tns:Anmeldedatum>
    <tns:Adresse>
      <tns:Strasse>Holzweg</tns:Strasse>
      <tns:Hausnummer>1</tns:Hausnummer>
      <tns:PLZ>51702</tns:PLZ>
      <tns:Ort>Bergneustadt</tns:Ort>
    </tns:Adresse>
    <tns:AnzahlSchnaeppchen>1</tns:AnzahlSchnaeppchen>
    <tns:GemeldeteSchnaeppchen>
      <tns:Schnaeppchen>2</tns:Schnaeppchen>
    </tns:GemeldeteSchnaeppchen>
    <tns:Bewertung>Neuling</tns:Bewertung>
  </tns:Benutzer>
  
  <tns:Benutzer>
    <tns:Id>3</tns:Id>
    <tns:Benutzername>ProfitGeier</tns:Benutzername>
    <tns:Passwort>123</tns:Passwort>
    <tns:Name>Schmidt</tns:Name>
    <tns:Vorname>Kevin</tns:Vorname>
    <tns:EMail>Kevin@Schmi.dt</tns:EMail>
    <tns:Anmeldedatum>2012-01-23</tns:Anmeldedatum>
    <tns:Adresse>
      <tns:Strasse>Holzweg</tns:Strasse>
      <tns:Hausnummer>13</tns:Hausnummer>
      <tns:PLZ>51702</tns:PLZ>
      <tns:Ort>Bergneustadt</tns:Ort>
    </tns:Adresse>
    <tns:AnzahlSchnaeppchen>3</tns:AnzahlSchnaeppchen>
    <tns:GemeldeteSchnaeppchen>
      <tns:Schnaeppchen>1</tns:Schnaeppchen>
      <tns:Schnaeppchen>35</tns:Schnaeppchen>
      <tns:Schnaeppchen>56</tns:Schnaeppchen>
    </tns:GemeldeteSchnaeppchen>
    <tns:Bewertung>Sehr Gut</tns:Bewertung>
  </tns:Benutzer>
</tns:Benutzerprofile>
