=== Navarone/WBA2_SS13_Phase2/WBA2_Phase2/src/schnaeppchen/Schnaeppchen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Schnaeppchen" xmlns:tns="http://www.example.org/Schnaeppchen" elementFormDefault="qualified">
	<xs:element name="Schnaeppchenxyz">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Schnaeppchen" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ID" type="xs:int"/>
							<xs:element name="Titel" type="xs:string" />
							<xs:element name="Benutzer" type="xs:int"/>
							<xs:element name="Kategorie">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Elektronik"/>
										<xs:enumeration value="Kategorie2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Bild" type="xs:anyURI" minOccurs="0"/>
							<xs:element name="URL" type="xs:anyURI" minOccurs="0"/>
							<xs:element name="Markt" type="xs:int" maxOccurs="unbounded"/>
							<xs:element name="Preise">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Preis" type="xs:string"/>
										<xs:element name="UVP" type="xs:string" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="Waehrung">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Euro"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="Text" type="xs:string"/>
							<xs:element name="Datum">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Tag" type="xs:date"/>
										<xs:element name="Uhrzeit" type="xs:time"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Kommentare" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Kommentar" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Text" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="Autor" type="xs:string"/>
												<xs:attribute name="Datum" type="xs:date"/>
												<xs:attribute name="Uhrzeit" type="xs:time"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Navarone/WBA2_SS13_Phase2/WBA2_Phase2/src/Schnaeppchen.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Schnaeppchenxyz xmlns:tns="http://www.example.org/Schnaeppchen" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Schnaeppchen Schnaeppchen.xsd ">
  <tns:Schnaeppchen>
    <tns:ID>1</tns:ID>
    <tns:Titel>Fernseher</tns:Titel>
    <tns:Benutzer>3</tns:Benutzer>
    <tns:Kategorie>Elektronik</tns:Kategorie>
    <tns:Bild>http://blog.prinz.de/grand-prix/files/fernseher.jpg</tns:Bild>
    <tns:Markt>2</tns:Markt>
    <tns:Markt>21</tns:Markt>
    <tns:Preise Waehrung="Euro">
      <tns:Preis>599</tns:Preis>
      <tns:UVP>999</tns:UVP>
    </tns:Preise>
    <tns:Text>Super Fernseher zum Super Preis. Jetzt bei Aldi!</tns:Text>
    <tns:Datum>
      <tns:Tag>2013-04-30</tns:Tag>
      <tns:Uhrzeit>21:44:00</tns:Uhrzeit>
    </tns:Datum>
    <tns:Kommentare>
    	<tns:Kommentar Autor="Marvin" Datum="2013-04-30" Uhrzeit="22:14:00">
    		<tns:Text>Super Angebot!</tns:Text>
    	</tns:Kommentar>
    	<tns:Kommentar Autor="Kevin" Datum="2013-04-30" Uhrzeit="22:23:00">
    		<tns:Text>Morgen gleich hinfahren und kaufen!</tns:Text>
    	</tns:Kommentar>
    </tns:Kommentare>
  </tns:Schnaeppchen>
  
  <tns:Schnaeppchen>
    <tns:ID>2</tns:ID>
    <tns:Titel>Laptop</tns:Titel>
    <tns:Benutzer>2</tns:Benutzer>
    <tns:Kategorie>Elektronik</tns:Kategorie>
    <tns:Bild>http://www.digitaltrends.com/wp-content/uploads/2012/10/samsung-series-5-ultra-touch.jpeg</tns:Bild>
    <tns:Markt>1</tns:Markt>
    <tns:Preise Waehrung="Euro">
      <tns:Preis>899</tns:Preis>
      <tns:UVP>1399</tns:UVP>
    </tns:Preise>
    <tns:Text>Super Laptop zum Super Preis. Jetzt bei Amazon!</tns:Text>
    <tns:Datum>
      <tns:Tag>2013-05-01</tns:Tag>
      <tns:Uhrzeit>14:13:00</tns:Uhrzeit>
    </tns:Datum>
    <tns:Kommentare>
    	<tns:Kommentar Autor="Fritz" Datum="2013-05-01" Uhrzeit="15:24:00">
    		<tns:Text>Echt Guenstig!</tns:Text>
    	</tns:Kommentar>
    	<tns:Kommentar Autor="Mario" Datum="2013-05-01" Uhrzeit="17:11:00">
    		<tns:Text>Direkt bestellt!</tns:Text>
    	</tns:Kommentar>
    </tns:Kommentare>
  </tns:Schnaeppchen>
</tns:Schnaeppchenxyz>
